name: Weekly PR to merge 'development' to 'main'


on:
  # Triggers every Thursday 8:00AM PDT
  schedule:
  - cron: '*/5 * * * *'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with: { ref: development }
      
      - name: Create PR
        uses: thomaseizinger/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: ${{ github.ref }}
          base: main
          title: 'An automatically created PR!'
