name: Weekly PR to merge 'development' to 'main'


on:
  # Triggers every Thursday 8:00AM PDT
  schedule:
  - cron: '*/5 * * * *'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          reviewers: DaleCS
          branch: development
